### ISSUE TITLE
Why are you storing this parm? ModelCore.PoissonDistribution.Lambda

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-SCRPPLE#107]
At PlugIn L650 and L685, why are you storing it in Poisson lamba?  It seems unnecessary to me.
possibleIgnitions=ModelCore.PoissonDistribution.Lambda

This seems like it would work fine: 
double possibleIgnitions = Math.Pow(Math.E, (b0 + (b1 * fireWeatherIndex)));

I guess my question is: where is this used? ModelCore.PoissonDistribution.Lambda

**Comment by ZacharyRobbins** [comment]
My understanding of that function is that is calling a draw from a random Poisson distribution with mean and variance Lambda. In this case Lambda is exp**(b0+b1*fireWeatherIndex).  The resulting variable is the number of ignitions.  The mean of the Poisson distribution you describe above is not equivocal and discounts the variance in the distribution.  It would make it mechanistic rather than statistical with regard to those variables.  Did this result in a larger problem?
