### ISSUE TITLE
Starting values of PET and ET

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-SCRPPLE#140]
It would be great to allow the user to input starting values of PET and ET in the Scrpple input file so you wouldn't have to throw out the first year of Scrpple output.

**Comment by tucker-furniss** [comment]
+1 request for this. 
It appears that it isn't just the first year that is thrown out, it is the first year _in which there is a fire in a given Ecoregion_. So if you have small Ecoregions that don't get an ignition in the first year, the values of previous year PET and water deficit will be 0 for the first fire in that Ecoregion, or the first succession timestep (whichever event happens first). See attached figure showing previous year PET as a function of simulation year (succession timestep is 10 years). The problem that this creates is that if the user has a non-zero value for the previous year climate parameters in the "site-mortality" equation (i.e., dNBR equation), dNBR is not calculated correctly (because previous year PET and Deficit are 0). The second figure here shows this - the distribution of dNBR values before year 10 is distinctly different compared to dNBR values after year 10 (first sucession timestep). 

Some ideas to fix this are: 1) at initialization, SCRPPLE could calculate Year0 PET and Deficit values (the issue would persist for year 0, but all subsequent years would be fixed). 2) If previous year PET and Deficit are 0, use current year values instead. 3) Use user-supplied PET and Deficit values.  

Thanks!
-Tucker


![image](https://user-images.githubusercontent.com/81191951/151869633-9965b7b7-a552-49e9-982d-0fe938b7fcfc.png)

![image](https://user-images.githubusercontent.com/81191951/151872861-b0ac99f2-a4bf-4e8c-86ae-87e5407878cc.png)

**Comment by rmscheller** [comment]
Tucker,

I assume you mean that you want PET and CWD to have a default time zero value, correct?

**Comment by rmscheller** [comment]
Check out https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/blob/master/src/FireEvent.cs
L321-324 and L327-331.

Is this the behavior you would like?

**Comment by tucker-furniss** [comment]
Yeah, I think that default time 0 values would solve the problem. Thanks!

**Comment by tucker-furniss** [comment]
I see the commit on Feb. 27, but the edits in FireEvent.cs are commented out. Is the update ready to implement or are we waiting for some other changes to release this fix as part of a new version (3.2.2)?

**Comment by rmscheller** [comment]
Tucker,

Please test v3.2.2.  I'll update documentation and release after your testing completed.

Cheers,

Rob

**Comment by tucker-furniss** [comment]
I tested v3.2.2 and it works perfectly. Thanks Rob!

**Comment by rmscheller** [comment]
Tested by Tucker and released.
