### ISSUE TITLE
RX burns do not cover enough of required RX burn per year

### ISSUE THREAD

**Issue by ppettus** [LANDIS-II-Foundation/Extension-SCRPPLE#85]
I checked it out the new scrapple and unfortunately there is still the same problem.

https://github.com/LANDIS-II-Foundation/Extension-SCRPPLE/blob/master/deploy/installer/LANDIS-II-V7%20SCRAPPLE%202.2.3-setup.exe

See new attach map with three years of data. Still not enough RX burn to cover the required area of burns for a burn cycle year.  One per day burn, and we don't even know what the RX burn window (start and stop date) for a typical year is yet, maybe a smaller window would have to compact multiple burns into a day.

![Missing_RX_Dynamic_Burn](https://user-images.githubusercontent.com/35970676/56319635-1bcbe480-6117-11e9-8eda-378c2de31925.jpg)

Please use the most recent version of the files in git link below, as some parameters and GIS files might have been changed.

https://github.com/LANDIS-II-Foundation/Project-Fort-Bragg-NC/tree/master/Testing/Rx_Fire_040219

**Comment by rmscheller** [comment]
Paul,
My conversations with Ft. Bragg were very informative.  They conduct an average of 6.5 burns per day, up to 10.  I propose we amend the inputs to allow this rather than the equation that I outlined.  We also need to set a Day-of-Year start and stop and alternatives to FWI as the burn parameter.  I'll outline in notes for your review.
